name: Deploy on Shuttle

on: 
    push:
        branches: master
        paths:
            - src/**

jobs:
    deploy:
        name: Deploy on Shuttle
        runs-on: ubuntu-latest
        steps:
            -   uses: shuttle-hq/deploy-action@main
                with:
                    deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
                    secrets: |
                        DISCORD_TOKEN = '${{ secrets.DISCORD_TOKEN }}'

